"""Helper functions for formatting GitHub comments."""
def format_github_comment(issue_data):
    """Format issue as GitHub comment."""
    severity_emoji = {
        'critical': '🔴',
        'major': '🟠',
        'minor': '🟡',
        'info': 'ℹ️'
    }
    emoji = severity_emoji.get(issue_data.get('severity', 'minor'), 'ℹ️')
    
    comment = f"""## {emoji} {issue_data.get('severity', 'minor').title()}: {issue_data.get('title', 'Issue')}

**File**: `{issue_data.get('file', 'unknown')}:{issue_data.get('line', '?')}`

**Issue**: {issue_data.get('description', 'No description')}

"""
    
    if issue_data.get('code_snippet'):
        comment += f"**Code**:\n```\n{issue_data.get('code_snippet')}\n```\n\n"
    
    if issue_data.get('evidence'):
        comment += "**Evidence**:\n"
        for evidence in issue_data.get('evidence', [])[:3]:
            comment += f"- {evidence}\n"
        comment += "\n"
    
    suggested_fix = issue_data.get('suggested_fix', {})
    if suggested_fix and suggested_fix.get('code'):
        comment += f"**Suggested Fix**:\n```\n{suggested_fix.get('code')}\n```\n\n"
        if suggested_fix.get('explanation'):
            comment += f"_{suggested_fix.get('explanation')}_\n\n"
    
    if issue_data.get('references'):
        comment += f"**References**: {', '.join(issue_data.get('references', []))}\n\n"
    
    comment += f"**Confidence**: {int(issue_data.get('confidence', 0.5) * 100)}%\n\n"
    comment += "---\n*Generated by CodeBuster AI Review*"
    
    return comment

